WADIZ:
  wadiz_id: USER_ID
  wadiz_pw: PASSWORD
  wadiz_file_path: wadiz.xlsx

NEWS:
  start_date: '2019.06.01'
  end_date: '2019.08.14'
  news_keyword: '크라우드펀딩'
  news_file_path: navernews_크라우드펀딩.xlsx
  max_num: 3999